/**
 * @file /src/editor/materials/index.tsx
 * @description
 * 物料系统的"自动化注册中心"。
 *
 * v2 架构：统一使用 ComponentProtocol 格式
 * - 所有组件使用 meta.tsx + index.tsx 结构
 * - 脚本生成 Partial<ComponentProtocol> 用于补全 setter 和 events
 *
 * 本文件利用 Vite 的 `import.meta.glob` 功能，动态扫描 `/materials` 目录下
 * 所有符合规范的物料组件，并将它们整合成一个 `materials` 配置数组。
 *
 * @module Materials/Index
 */
import {
  type ComponentConfig,
  type ComponentProtocol,
  type EventConfig,
  type SetterConfig,
} from "../types/component-protocol";

/**
 * @description 动态、同步地导入所有"手写物料"的 `meta.tsx` 文件。
 * - 避免与自动生成目录 `/_generated` 重复扫描。
 * - `eager: true`: 构建时直接打包进来，模块加载即得。
 * - `import: "default"`: 仅取默认导出。
 */
const manualMetasAll = import.meta.glob<ComponentConfig>("./**/meta.tsx", {
  eager: true,
  import: "default",
});
// 过滤掉 _generated 目录
const manualMetas = Object.fromEntries(
  Object.entries(manualMetasAll).filter(([k]) => !k.startsWith("./_generated/"))
);

/**
 * @description 同步引入脚本生成的 antd 组件 meta（位于 `/_generated` 目录）。
 * 生成的是 Partial<ComponentProtocol> 格式，用于补全手动 meta 缺失的 setter 和 events
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - 由生成脚本保证存在
import * as autoGeneratedMetasNS from "./_generated";

// 将自动生成的 meta 转为 Map，便于查找
const autoGeneratedMetas = autoGeneratedMetasNS as Record<
  string,
  Partial<ComponentProtocol>
>;
const generatedMetaMap = new Map(
  Object.values(autoGeneratedMetas).map((m) => [m.name, m])
);

/**
 * @description 将"手写物料"的 meta 映射为完整的 `ComponentConfig`。
 * 所有组件都使用 ComponentProtocol 格式
 */
const manualList: ComponentConfig[] = Object.values(manualMetas);

/**
 * @description 工具：合并事件，按 name 去重（手写优先，生成的补缺）
 */
function mergeEvents(manual?: EventConfig[], generated?: EventConfig[]) {
  const out: EventConfig[] = [...(manual ?? [])];
  for (const e of generated ?? []) {
    if (!out.some((x) => x.name === e.name)) out.push(e);
  }
  return out;
}

/**
 * @description 获取组件的 parentTypes
 */
function getParentTypes(config: ComponentConfig): string[] | undefined {
  return config.editor.parentTypes;
}

/**
 * @description 最终合并策略：
 * - 以"手写"项为基底
 * - 用"自动生成"补齐缺省字段（setter, events, defaultProps）
 */
const mergedMaterials: ComponentConfig[] = manualList.map((man) => {
  const generatedMeta = generatedMetaMap.get(man.name);

  // 如果手动 meta 没写 setter 或 events，从自动生成的补全
  const needsMerge =
    !man.setter ||
    man.setter.length === 0 ||
    !man.events ||
    man.events.length === 0;

  if (needsMerge && generatedMeta) {
    return {
      ...man,
      // 手动优先，自动补全
      setter:
        man.setter && man.setter.length > 0
          ? man.setter
          : ((generatedMeta.setter ?? []) as SetterConfig[]),
      events: mergeEvents(man.events, generatedMeta.events as EventConfig[]),
      defaultProps: {
        ...(generatedMeta.defaultProps ?? {}),
        ...man.defaultProps,
      },
    };
  }

  return man;
});

/**
 * @description 最终导出的、包含了所有物料完整配置的数组。
 * 这是整个低代码编辑器的"物料库"。
 */
export const materials: ComponentConfig[] = mergedMaterials;

// 导出类型和工具函数，供其他模块使用
export { getParentTypes };
export type { ComponentConfig, ComponentProtocol };
